/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'


export function StreetLight({ streatlight = "#ffdaab", ...props }: any) {
    const { nodes, materials } = useGLTF('/model/street_light/stylized_street_light.gltf') as any

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group name="SM_Street_Light">

                        {/* --- THE EMISSION / BULB PART --- */}
                        <mesh
                            name="SM_Street_Light_M_Street_Light_Emission_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.SM_Street_Light_M_Street_Light_Emission_0.geometry}
                        >
                            {/* The physical light source */}
                            <pointLight
                                intensity={20}
                                distance={25}
                                decay={2}
                                color={streatlight}
                                castShadow
                                shadow-mapSize={[1024, 1024]}
                            />

                            {/* Applying the material with glowing (emissive) properties */}
                            <meshStandardMaterial
                                {...materials.M_Street_Light_Emission}
                                emissive="#ffdaab"
                                emissiveIntensity={5}
                            />
                        </mesh>

                        {/* --- THE POLE PART --- */}
                        <mesh
                            name="SM_Street_Light_M_Street_Light_Pole_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.SM_Street_Light_M_Street_Light_Pole_0.geometry}
                            material={materials.M_Street_Light_Pole}
                        />

                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/street_light/stylized_street_light.gltf')