/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'




export function StreetLight(props: any) {
    const { nodes, materials } = useGLTF('/model/street_light/stylized_street_light.gltf') as any
    return (
        <group {...props} dispose={null}>
            <group>
                <group name="stylized_street_light" userData={{ name: 'stylized_street_light' }}>
                    <group
                        name="Sketchfab_model"
                        rotation={[-Math.PI / 2, 0, 0]}
                        userData={{ name: 'Sketchfab_model' }}>
                        <group
                            name="SM_Street_Lightfbx"
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.01}
                            userData={{ name: 'SM Street Light.fbx' }}>
                            <group name="RootNode" userData={{ name: 'RootNode' }}>
                                <group name="SM_Street_Light" userData={{ name: 'SM_Street_Light' }}>
                                    <mesh
                                        name="SM_Street_Light_M_Street_Light_Emission_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.SM_Street_Light_M_Street_Light_Emission_0.geometry}
                                        material={materials.M_Street_Light_Emission}
                                        userData={{ name: 'SM_Street_Light_M_Street_Light_Emission_0' }}
                                    />
                                    <mesh
                                        name="SM_Street_Light_M_Street_Light_Pole_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.SM_Street_Light_M_Street_Light_Pole_0.geometry}
                                        material={materials.M_Street_Light_Pole}
                                        userData={{ name: 'SM_Street_Light_M_Street_Light_Pole_0' }}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/street_light/stylized_street_light.gltf')
