/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Harex-Studio (https://sketchfab.com/HAREX-STUDIO)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/indian-fort-be4432b8b18b451eb9081e959e348e6e
Title: INDIAN FORT
*/

import { useGLTF } from '@react-three/drei'


export function Temple(props: any) {
  const { nodes, materials } = useGLTF('/model/temple/indian_fort.glb') as any
  return (

    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Doom} />
      <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.wall} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Roof_Top}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.pARAPET_WALL}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.pARAPET_sLAB}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.floor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Doom_Support}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.ceiling}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials['Material.002']}
      />
    </group>

  )
}

useGLTF.preload('/model/temple/indian_fort.glb')


