/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PineTree(props) {
    const { nodes, materials } = useGLTF('/model/tree/PineTree.gltf')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Resource_PineTree_Group_1.geometry}
                    material={materials.Wood}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Resource_PineTree_Group_2.geometry}
                    material={materials.Green}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/model/tree/PineTree.gltf')