

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PoorHouse(props) {
    const { nodes, materials } = useGLTF('/model/House/PoorHouse/PoorHouse.gltf')
    return (
        <group {...props} dispose={null}>
            <group scale={10}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.house_type07_1.geometry}
                    material={materials.border}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.house_type07_2.geometry}
                    material={materials.window}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.house_type07_3.geometry}
                    material={materials.roof}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.house_type07_4.geometry}
                    material={materials.door}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.house_type07_5.geometry}
                    material={materials._defaultMat}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/model/House/PoorHouse/PoorHouse.gltf')






