/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Grass } from '../../Grass/Grass'

export function NormalTree(props) {
    const { nodes, materials } = useGLTF('/model/tree/NormalTree.gltf')
    return (
        <>
            <Grass scale={[10, 10, 10]} position={[0, -1, 1]} />
            <group {...props} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={materials.Material}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={46.324}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere003.geometry}
                    material={materials['Material.001']}
                    position={[0.405, 6.347, -0.703]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={139.01}
                />
            </group>
        </>
    )
}

useGLTF.preload('/model/tree/NormalTree.gltf')



