/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export function ComputerDesk(props) {
    const { nodes, materials } = useGLTF('/model/computerDesk.glb')
    return (
        <group {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode" userData={{ name: 'RootNode' }}>
                    <group
                        name="Dual_Monitors_on_sit-stand_arm"
                        position={[-0.3, 1.4, -6.3]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={30.2}
                        userData={{ name: 'Dual Monitors on sit-stand arm' }}>
                        <group
                            name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|"
                            userData={{ name: 'Dual Monitors on sit-stand arm|group329542522|Dupli|' }}>
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1"
                                castShadow
                                receiveShadow
                                geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1'].geometry}
                                material={materials['mat22.010']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2"
                                castShadow
                                receiveShadow
                                geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2'].geometry}
                                material={materials['mat23.015']}
                            />
                        </group>
                        <group
                            name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1"
                            userData={{ name: 'Dual Monitors on sit-stand arm|group576947092|Dupli|1' }}>
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1"
                                castShadow
                                receiveShadow
                                geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1'].geometry}
                                material={materials['mat22.010']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2"
                                castShadow
                                receiveShadow
                                geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2'].geometry}
                                material={materials['mat23.015']}
                            />
                        </group>
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1219313228|Dupli|2' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1783798096|Dupli|3' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group625259463|Dupli|4' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group112678593|Dupli|5' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group575146565|Dupli|6' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1462626064|Dupli|7' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1746518091|Dupli|8' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group2060347243|Dupli|9' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group929043094|Dupli|10' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group2063576334|Dupli|11' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1698824667|Dupli|12' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group2070617275|Dupli|13' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group710626981|Dupli|14' }}
                        />
                        <group
                            name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15"
                            userData={{ name: 'Dual Monitors on sit-stand arm|group150401702|Dupli|15' }}>
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1'].geometry
                                }
                                material={materials['mat22.010']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2'].geometry
                                }
                                material={materials['mat23.015']}
                            />
                        </group>
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group2128326706|Dupli|16' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17'].geometry}
                            material={materials['mat23.015']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group974294459|Dupli|17' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1658787459|Dupli|18' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1896072715|Dupli|19' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group451364077|Dupli|20' }}
                        />
                        <mesh
                            name="Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21"
                            castShadow
                            receiveShadow
                            geometry={nodes['Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21'].geometry}
                            material={materials['mat22.010']}
                            userData={{ name: 'Dual Monitors on sit-stand arm|group786212531|Dupli|21' }}
                        />
                        <group
                            name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22"
                            userData={{ name: 'Dual Monitors on sit-stand arm|group860618825|Dupli|22' }}>
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1'].geometry
                                }
                                material={materials['mat22.010']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2'].geometry
                                }
                                material={materials['mat23.015']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3'].geometry
                                }
                                material={materials['mat21.012']}
                            />
                        </group>
                        <group
                            name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23"
                            userData={{ name: 'Dual Monitors on sit-stand arm|group1691283673|Dupli|23' }}>
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1'].geometry
                                }
                                material={materials['mat22.010']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2'].geometry
                                }
                                material={materials['mat23.015']}
                            />
                            <mesh
                                name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3"
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3'].geometry
                                }
                                material={materials['mat21.012']}
                            />
                        </group>
                    </group>
                    <group
                        name="Keyboard"
                        position={[-0.3, 1.2, -6.7]}
                        rotation={[-1.6, 0, 3.1]}
                        scale={20.5}
                        userData={{ name: 'Keyboard' }}>
                        <mesh
                            name="Keyboard|group425587018|Dupli|"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group425587018|Dupli|'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group425587018|Dupli|' }}
                        />
                        <mesh
                            name="Keyboard|group311988427|Dupli|1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group311988427|Dupli|1'].geometry}
                            material={materials['mat22.011']}
                            userData={{ name: 'Keyboard|group311988427|Dupli|1' }}
                        />
                        <mesh
                            name="Keyboard|group96314515|Dupli|2"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group96314515|Dupli|2'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group96314515|Dupli|2' }}
                        />
                        <mesh
                            name="Keyboard|group449779970|Dupli|3"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group449779970|Dupli|3'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group449779970|Dupli|3' }}
                        />
                        <mesh
                            name="Keyboard|group2106755496|Dupli|4"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group2106755496|Dupli|4'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group2106755496|Dupli|4' }}
                        />
                        <mesh
                            name="Keyboard|group1753917514|Dupli|5"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1753917514|Dupli|5'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1753917514|Dupli|5' }}
                        />
                        <mesh
                            name="Keyboard|group1529968652|Dupli|6"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1529968652|Dupli|6'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1529968652|Dupli|6' }}
                        />
                        <mesh
                            name="Keyboard|group252681800|Dupli|7"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group252681800|Dupli|7'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group252681800|Dupli|7' }}
                        />
                        <mesh
                            name="Keyboard|group1581414308|Dupli|8"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1581414308|Dupli|8'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1581414308|Dupli|8' }}
                        />
                        <mesh
                            name="Keyboard|group295085766|Dupli|9"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group295085766|Dupli|9'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group295085766|Dupli|9' }}
                        />
                        <mesh
                            name="Keyboard|group384612072|Dupli|10"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group384612072|Dupli|10'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group384612072|Dupli|10' }}
                        />
                        <mesh
                            name="Keyboard|group150579309|Dupli|11"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group150579309|Dupli|11'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group150579309|Dupli|11' }}
                        />
                        <mesh
                            name="Keyboard|group1675960081|Dupli|12"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1675960081|Dupli|12'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1675960081|Dupli|12' }}
                        />
                        <mesh
                            name="Keyboard|group287159489|Dupli|13"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group287159489|Dupli|13'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group287159489|Dupli|13' }}
                        />
                        <mesh
                            name="Keyboard|group1956214489|Dupli|14"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1956214489|Dupli|14'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1956214489|Dupli|14' }}
                        />
                        <mesh
                            name="Keyboard|group196400395|Dupli|15"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group196400395|Dupli|15'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group196400395|Dupli|15' }}
                        />
                        <mesh
                            name="Keyboard|group954813675|Dupli|16"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group954813675|Dupli|16'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group954813675|Dupli|16' }}
                        />
                        <mesh
                            name="Keyboard|group706802639|Dupli|17"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group706802639|Dupli|17'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group706802639|Dupli|17' }}
                        />
                        <mesh
                            name="Keyboard|group1976194690|Dupli|18"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1976194690|Dupli|18'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1976194690|Dupli|18' }}
                        />
                        <mesh
                            name="Keyboard|group1152190519|Dupli|19"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1152190519|Dupli|19'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1152190519|Dupli|19' }}
                        />
                        <mesh
                            name="Keyboard|group2074153597|Dupli|20"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group2074153597|Dupli|20'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group2074153597|Dupli|20' }}
                        />
                        <mesh
                            name="Keyboard|group1629609685|Dupli|21"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1629609685|Dupli|21'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1629609685|Dupli|21' }}
                        />
                        <mesh
                            name="Keyboard|group1030983910|Dupli|22"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1030983910|Dupli|22'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1030983910|Dupli|22' }}
                        />
                        <mesh
                            name="Keyboard|group145618305|Dupli|23"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group145618305|Dupli|23'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group145618305|Dupli|23' }}
                        />
                        <mesh
                            name="Keyboard|group826580911|Dupli|24"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group826580911|Dupli|24'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group826580911|Dupli|24' }}
                        />
                        <mesh
                            name="Keyboard|group601803475|Dupli|25"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group601803475|Dupli|25'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group601803475|Dupli|25' }}
                        />
                        <mesh
                            name="Keyboard|group1589752359|Dupli|26"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1589752359|Dupli|26'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1589752359|Dupli|26' }}
                        />
                        <mesh
                            name="Keyboard|group806343109|Dupli|27"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group806343109|Dupli|27'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group806343109|Dupli|27' }}
                        />
                        <mesh
                            name="Keyboard|group1238060299|Dupli|28"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1238060299|Dupli|28'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1238060299|Dupli|28' }}
                        />
                        <mesh
                            name="Keyboard|group801095923|Dupli|29"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group801095923|Dupli|29'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group801095923|Dupli|29' }}
                        />
                        <mesh
                            name="Keyboard|group418912012|Dupli|30"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group418912012|Dupli|30'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group418912012|Dupli|30' }}
                        />
                        <mesh
                            name="Keyboard|group205302596|Dupli|31"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group205302596|Dupli|31'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group205302596|Dupli|31' }}
                        />
                        <mesh
                            name="Keyboard|group1323238240|Dupli|32"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1323238240|Dupli|32'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1323238240|Dupli|32' }}
                        />
                        <mesh
                            name="Keyboard|group1571332333|Dupli|33"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1571332333|Dupli|33'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1571332333|Dupli|33' }}
                        />
                        <mesh
                            name="Keyboard|group34220672|Dupli|34"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group34220672|Dupli|34'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group34220672|Dupli|34' }}
                        />
                        <mesh
                            name="Keyboard|group1272091893|Dupli|35"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1272091893|Dupli|35'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1272091893|Dupli|35' }}
                        />
                        <mesh
                            name="Keyboard|group1899843208|Dupli|36"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1899843208|Dupli|36'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1899843208|Dupli|36' }}
                        />
                        <mesh
                            name="Keyboard|group42243725|Dupli|37"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group42243725|Dupli|37'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group42243725|Dupli|37' }}
                        />
                        <mesh
                            name="Keyboard|group2146178072|Dupli|38"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group2146178072|Dupli|38'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group2146178072|Dupli|38' }}
                        />
                        <mesh
                            name="Keyboard|group1316349499|Dupli|39"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1316349499|Dupli|39'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1316349499|Dupli|39' }}
                        />
                        <mesh
                            name="Keyboard|group1754683637|Dupli|40"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1754683637|Dupli|40'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1754683637|Dupli|40' }}
                        />
                        <mesh
                            name="Keyboard|group475225180|Dupli|41"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group475225180|Dupli|41'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group475225180|Dupli|41' }}
                        />
                        <mesh
                            name="Keyboard|group77921105|Dupli|42"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group77921105|Dupli|42'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group77921105|Dupli|42' }}
                        />
                        <mesh
                            name="Keyboard|group96968687|Dupli|43"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group96968687|Dupli|43'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group96968687|Dupli|43' }}
                        />
                        <mesh
                            name="Keyboard|group268332703|Dupli|44"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group268332703|Dupli|44'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group268332703|Dupli|44' }}
                        />
                        <mesh
                            name="Keyboard|group993315105|Dupli|45"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group993315105|Dupli|45'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group993315105|Dupli|45' }}
                        />
                        <mesh
                            name="Keyboard|group1740918352|Dupli|46"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1740918352|Dupli|46'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1740918352|Dupli|46' }}
                        />
                        <mesh
                            name="Keyboard|group588539140|Dupli|47"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group588539140|Dupli|47'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group588539140|Dupli|47' }}
                        />
                        <mesh
                            name="Keyboard|group729811280|Dupli|48"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group729811280|Dupli|48'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group729811280|Dupli|48' }}
                        />
                        <mesh
                            name="Keyboard|group573547017|Dupli|49"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group573547017|Dupli|49'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group573547017|Dupli|49' }}
                        />
                        <mesh
                            name="Keyboard|group1180881246|Dupli|50"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1180881246|Dupli|50'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1180881246|Dupli|50' }}
                        />
                        <mesh
                            name="Keyboard|group687259746|Dupli|51"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group687259746|Dupli|51'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group687259746|Dupli|51' }}
                        />
                        <mesh
                            name="Keyboard|group45382983|Dupli|52"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group45382983|Dupli|52'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group45382983|Dupli|52' }}
                        />
                        <mesh
                            name="Keyboard|group1149852049|Dupli|53"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1149852049|Dupli|53'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1149852049|Dupli|53' }}
                        />
                        <mesh
                            name="Keyboard|group790925258|Dupli|54"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group790925258|Dupli|54'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group790925258|Dupli|54' }}
                        />
                        <mesh
                            name="Keyboard|group873458270|Dupli|55"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group873458270|Dupli|55'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group873458270|Dupli|55' }}
                        />
                        <mesh
                            name="Keyboard|group616518658|Dupli|56"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group616518658|Dupli|56'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group616518658|Dupli|56' }}
                        />
                        <mesh
                            name="Keyboard|group2085389804|Dupli|57"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group2085389804|Dupli|57'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group2085389804|Dupli|57' }}
                        />
                        <mesh
                            name="Keyboard|group1075691498|Dupli|58"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1075691498|Dupli|58'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1075691498|Dupli|58' }}
                        />
                        <mesh
                            name="Keyboard|group2091112366|Dupli|59"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group2091112366|Dupli|59'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group2091112366|Dupli|59' }}
                        />
                        <mesh
                            name="Keyboard|group1764140354|Dupli|60"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1764140354|Dupli|60'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1764140354|Dupli|60' }}
                        />
                        <mesh
                            name="Keyboard|group1238428394|Dupli|61"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1238428394|Dupli|61'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1238428394|Dupli|61' }}
                        />
                        <mesh
                            name="Keyboard|group873558583|Dupli|62"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group873558583|Dupli|62'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group873558583|Dupli|62' }}
                        />
                        <mesh
                            name="Keyboard|group1486350934|Dupli|63"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1486350934|Dupli|63'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1486350934|Dupli|63' }}
                        />
                        <mesh
                            name="Keyboard|group1629393722|Dupli|64"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1629393722|Dupli|64'].geometry}
                            material={materials['mat21.013']}
                            userData={{ name: 'Keyboard|group1629393722|Dupli|64' }}
                        />
                        <mesh
                            name="Keyboard|group1870575723|Dupli|65"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group1870575723|Dupli|65'].geometry}
                            material={materials['mat16.006']}
                            userData={{ name: 'Keyboard|group1870575723|Dupli|65' }}
                        />
                        <mesh
                            name="Keyboard|group877249531|Dupli|66"
                            castShadow
                            receiveShadow
                            geometry={nodes['Keyboard|group877249531|Dupli|66'].geometry}
                            material={materials['mat9.002']}
                            userData={{ name: 'Keyboard|group877249531|Dupli|66' }}
                        />
                    </group>
                    <group
                        name="Mug_With_Office_Tool"
                        position={[-0.8, 0.9, -6.1]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={129.6}
                        userData={{ name: 'Mug With Office Tool' }}>
                        <mesh
                            name="Mug_With_Office_Tool|Mug_with_office_tools|Dupli|"
                            castShadow
                            receiveShadow
                            geometry={nodes['Mug_With_Office_Tool|Mug_with_office_tools|Dupli|'].geometry}
                            material={materials['Material.015']}
                            scale={100}
                            userData={{ name: 'Mug With Office Tool|Mug with office tools|Dupli|' }}
                        />
                    </group>
                    <group
                        name="Soda001"
                        position={[-1.2, 0.9, -6.5]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={18.6}
                        userData={{ name: 'Soda.001' }}>
                        <group
                            name="Soda001|Soda|Dupli|"
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={100}
                            userData={{ name: 'Soda.001|Soda|Dupli|' }}>
                            <mesh
                                name="Soda001|Soda|Dupli|_1"
                                castShadow
                                receiveShadow
                                geometry={nodes['Soda001|Soda|Dupli|_1'].geometry}
                                material={materials['White.005']}
                            />
                            <mesh
                                name="Soda001|Soda|Dupli|_2"
                                castShadow
                                receiveShadow
                                geometry={nodes['Soda001|Soda|Dupli|_2'].geometry}
                                material={materials['Red.002']}
                            />
                        </group>
                    </group>
                    <group
                        name="Notebook"
                        position={[0.3, 0.9, -6.5]}
                        rotation={[-Math.PI / 2, 0, -2.9]}
                        scale={3.1}
                        userData={{ name: 'Notebook' }}>
                        <group
                            name="Notebook|Notebook_Cube041|Dupli|"
                            userData={{ name: 'Notebook|Notebook_Cube.041|Dupli|' }}>
                            <mesh
                                name="Notebook|Notebook_Cube041|Dupli|_1"
                                castShadow
                                receiveShadow
                                geometry={nodes['Notebook|Notebook_Cube041|Dupli|_1'].geometry}
                                material={materials['FFEB3B.002']}
                            />
                            <mesh
                                name="Notebook|Notebook_Cube041|Dupli|_2"
                                castShadow
                                receiveShadow
                                geometry={nodes['Notebook|Notebook_Cube041|Dupli|_2'].geometry}
                                material={materials['795548.003']}
                            />
                            <mesh
                                name="Notebook|Notebook_Cube041|Dupli|_3"
                                castShadow
                                receiveShadow
                                geometry={nodes['Notebook|Notebook_Cube041|Dupli|_3'].geometry}
                                material={materials['F44336.006']}
                            />
                        </group>
                    </group>
                    <mesh
                        name="Mousepad001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mousepad001.geometry}
                        material={materials.Mousepad}
                        position={[-1.1, 0.9, -6.9]}
                        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                        scale={[17.2, 21, 0.2]}
                        userData={{ name: 'Mousepad.001' }}
                    />
                    <group
                        name="Office_Phone001"
                        position={[0.3, 1, -6.2]}
                        rotation={[0, 0.1, Math.PI]}
                        scale={781.6}
                        userData={{ name: 'Office Phone.001' }}>
                        <mesh
                            name="Office_Phone001_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Office_Phone001_1.geometry}
                            material={materials['Light grey']}
                        />
                        <mesh
                            name="Office_Phone001_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Office_Phone001_2.geometry}
                            material={materials['Grey Plastic']}
                        />
                        <mesh
                            name="Office_Phone001_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Office_Phone001_3.geometry}
                            material={materials.Screen}
                        />
                        <mesh
                            name="Office_Phone001_4"
                            castShadow
                            receiveShadow
                            geometry={nodes.Office_Phone001_4.geometry}
                            material={materials['Dark Grey Plastic']}
                        />
                    </group>
                    <group
                        name="Calendar-8GqQAqxi3qk"
                        position={[-1.1, 0.9, -6.2]}
                        rotation={[-Math.PI / 2, 0, 2.8]}
                        scale={1.2}
                        userData={{ name: 'Calendar-8GqQAqxi3qk' }}>
                        <mesh
                            name="Calendar-8GqQAqxi3qk_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Calendar-8GqQAqxi3qk_1'].geometry}
                            material={materials.Calendar_Texture}
                        />
                        <mesh
                            name="Calendar-8GqQAqxi3qk_2"
                            castShadow
                            receiveShadow
                            geometry={nodes['Calendar-8GqQAqxi3qk_2'].geometry}
                            material={materials.Calendar_Aquamarine}
                        />
                        <mesh
                            name="Calendar-8GqQAqxi3qk_3"
                            castShadow
                            receiveShadow
                            geometry={nodes['Calendar-8GqQAqxi3qk_3'].geometry}
                            material={materials.Calendar_Ivory}
                        />
                        <mesh
                            name="Calendar-8GqQAqxi3qk_4"
                            castShadow
                            receiveShadow
                            geometry={nodes['Calendar-8GqQAqxi3qk_4'].geometry}
                            material={materials.FrontColor}
                        />
                    </group>
                    <group
                        name="Desk"
                        position={[-0.5, 0, -6.3]}
                        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                        scale={100}
                        userData={{ name: 'Desk' }}>
                        <mesh
                            name="Desk_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Desk_1.geometry}
                            material={materials.BlackCoatSteel}
                        />
                        <mesh
                            name="Desk_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Desk_2.geometry}
                            material={materials.GrayPlastic}
                        />
                        <mesh
                            name="Desk_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Desk_3.geometry}
                            material={materials.WhiteSteelScrew}
                        />
                        <mesh
                            name="Desk_4"
                            castShadow
                            receiveShadow
                            geometry={nodes.Desk_4.geometry}
                            material={materials.BlackPlastic}
                        />
                        <mesh
                            name="Desk_5"
                            castShadow
                            receiveShadow
                            geometry={nodes.Desk_5.geometry}
                            material={materials.BlackWood}
                        />
                    </group>
                    <mesh
                        name="Mouse001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mouse001.geometry}
                        material={materials['Material.001']}
                        position={[-1.1, 0.9, -6.9]}
                        rotation={[-Math.PI / 2, 0, -2.7]}
                        scale={10000}
                        userData={{ name: 'Mouse.001' }}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/computerDesk.glb')
