/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Man(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('model/Man/Man.gltf')
    const { actions, names } = useAnimations(animations, group)

    /**
     * idel animation
     */
    useEffect(() => {
        actions[names[0]]?.reset().fadeIn(0.5).play()
        return () => {
            actions[names[0]]?.fadeOut(0.5)
        }
    }, [])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="AuxScene">
                <group name="Walking">
                    <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <primitive object={nodes.mixamorigHips} />
                        <skinnedMesh
                            name="Guard02"
                            geometry={nodes.Guard02.geometry}
                            material={materials.Guard_02}
                            skeleton={nodes.Guard02.skeleton}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('model/Man/Man.gltf')


