// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useEffect, useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export function Man(props) {
//     const group = useRef()
//     const { nodes, materials, animations } = useGLTF('model/Man/Man.gltf')
//     const { actions, names } = useAnimations(animations, group)

//     /**
//      * idel animation
//      */
//     useEffect(() => {
//         actions[names[0]]?.reset().fadeIn(0.5).play()
//         return () => {
//             actions[names[0]]?.fadeOut(0.5)
//         }
//     }, [])
//     return (
//         <group ref={group} {...props} dispose={null}>
//             <group name="AuxScene">
//                 <group name="Walking">
//                     <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//                         <primitive object={nodes.mixamorigHips} />
//                         <skinnedMesh
//                             name="Guard02"
//                             geometry={nodes.Guard02.geometry}
//                             material={materials.Guard_02}
//                             skeleton={nodes.Guard02.skeleton}
//                         />
//                     </group>
//                 </group>
//             </group>
//         </group>
//     )
// }

// useGLTF.preload('model/Man/Man.gltf')



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export enum AnimationNames  {
    
        Clapping="HumanArmature|Man_Clapping",
        Death="HumanArmature|Man_Death",
        Idle="HumanArmature|Man_Idle",
        Jump="HumanArmature|Man_Jump",
        Punch="HumanArmature|Man_Punch",
        Run="HumanArmature|Man_Run",
        RunningJump="HumanArmature|Man_RunningJump",
        Sitting="HumanArmature|Man_Sitting",
        Standing="HumanArmature|Man_Standing",
        SwordSlash="HumanArmature|Man_SwordSlash",
        Walk= "HumanArmature|Man_Walk"
    
}

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Man(props) {
    
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/Man/Man.gltf')
  const { actions,names } = useAnimations(animations, group);

      useEffect(() => {
        actions[props.animationType]?.reset().fadeIn(0.5).play()
        return () => {
            actions[props.animationType]?.fadeOut(0.5)
        }
    }, [props.animationType])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="HumanArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Bone} />
          </group>
          <group name="BaseHuman" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="BaseHuman_1"
              geometry={nodes.BaseHuman_1.geometry}
              material={materials.Shirt}
              skeleton={nodes.BaseHuman_1.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_2"
              geometry={nodes.BaseHuman_2.geometry}
              material={materials.Pants}
              skeleton={nodes.BaseHuman_2.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_3"
              geometry={nodes.BaseHuman_3.geometry}
              material={materials.Eyes}
              skeleton={nodes.BaseHuman_3.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_4"
              geometry={nodes.BaseHuman_4.geometry}
              material={materials.Skin}
              skeleton={nodes.BaseHuman_4.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_5"
              geometry={nodes.BaseHuman_5.geometry}
              material={materials.Hair}
              skeleton={nodes.BaseHuman_5.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_6"
              geometry={nodes.BaseHuman_6.geometry}
              material={materials.Details}
              skeleton={nodes.BaseHuman_6.skeleton}
            />
            <skinnedMesh
              name="BaseHuman_7"
              geometry={nodes.BaseHuman_7.geometry}
              material={materials.TieTexture}
              skeleton={nodes.BaseHuman_7.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/Man/Man.gltf')




